FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

ARG MODEL_PROXY_URL="https://track2-fireworks-proxy.proxide-track2.workers.dev"
ARG FIREWORKS_MODEL="accounts/fireworks/models/kimi-k2p6"
ARG FIREWORKS_CAPTION_MODEL="accounts/fireworks/models/kimi-k2p6"

ENV MODEL_PROXY_URL=${MODEL_PROXY_URL} \
    FIREWORKS_MODEL=${FIREWORKS_MODEL} \
    FIREWORKS_CAPTION_MODEL=${FIREWORKS_CAPTION_MODEL} \
    FIREWORKS_JUDGE_MODEL=${FIREWORKS_MODEL} \
    FIREWORKS_SELECTOR_MODEL=${FIREWORKS_CAPTION_MODEL} \
    RUN_CHECKS=false \
    TRACK2_RUNTIME_TARGET_SECONDS=540 \
    TRACK2_HARD_DEADLINE_SECONDS=585 \
    TRACK2_PER_CLIP_DEADLINE_SECONDS=28 \
    TRACK2_FRAME_PROFILE=hybrid \
    TRACK2_MAX_FRAMES=5 \
    TRACK2_MODEL_CALL_RESERVE_SECONDS=75 \
    TRACK2_ENABLE_STYLE_RETRY=true \
    TRACK2_CANDIDATE_COUNT=4 \
    TRACK2_STAGE_DEADLINE_PERCEPTION=12 \
    TRACK2_STAGE_DEADLINE_CANDIDATES=10 \
    TRACK2_STAGE_DEADLINE_SELECTION=6 \
    TRACK2_OCR_ENABLED=true \
    TRACK2_CROP_ENABLED=true \
    TRACK2_MOTION_CLIP_ENABLED=true \
    FIREWORKS_CAPTION_MAX_TOKENS=800 \
    FIREWORKS_CREATIVE_TEMPERATURE=0.45 \
    FIREWORKS_MAX_RETRIES=1 \
    FIREWORKS_REQUEST_TIMEOUT_SECONDS=28

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501

ENTRYPOINT ["python", "-m", "track2_captioner.harness"]
